### ISSUE TITLE
Luxcore for 3ds max 2020

### ISSUE THREAD

**Issue by NarcisCalin** [LuxCoreRender/MaxToLux#18]
Would it be possible to add luxcore to 3ds max 2020?

**Comment by OmidGhotbi** [comment]
of course, I'm working on it, but as there are so many parameters left and 3dsMax is a bit hard to work with especially bug fix my hands are tight.
My goal is to add as much as possible features along with stability.

**Comment by NarcisCalin** [comment]
Understandable, thx for answering!

**Comment by OmidGhotbi** [comment]
you can expect the first 3dsmax 2020 release in the next 10 days, but it may not be as stable as it should be.

**Comment by NarcisCalin** [comment]
Can work for me, i want to play around with it. Will the caustics be supported?

**Comment by OmidGhotbi** [comment]
I'll do my best.

**Comment by OmidGhotbi** [comment]
3dsmax 2020 plugin avilable and can be download  here v0.5.4467-beta.3 [dlownload](https://github.com/LuxCoreRender/MaxToLux/releases/tag/0.5.4467)
