### ISSUE TITLE
Selecting one GPU is not working on multiple GPUs setup

### ISSUE THREAD

**Issue by a1-kh** [LuxCoreRender/MaxToLux#26]
Hi there TAO , long time no see  😄 .
Great news , i will try to check it more tonight.
- I noticed a problem, and i hope that it is easy to fix. When i try to choose one GPU, it uses both GPUs always, any thought 🏁 ? 
- Also I noticed that the CPU usage is always 100% too .

**Comment by OmidGhotbi** [comment]
Fixed in upcoming weekly build.

**Comment by OmidGhotbi** [comment]
fixed in v0.8.1904-beta build.
Avoid selecting intel base GPU, it's a bit slow and laggy.
