### ISSUE TITLE
lux glass: IOR custom value not translated to LuxCore

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#30]
3ds max 2021
lux glass: IOR custom value not translated to LuxCore. 
by default inner ior is set to 1.5, outher to 1.0 changing the values does not affect the render.
Same happen for lux architectural glass

**Comment by OmidGhotbi** [comment]
fixed in v0.8.1904-beta build.

**Comment by OmidGhotbi** [comment]
glass render dark at the moment, need to be fixed

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta
