### ISSUE TITLE
any lux light object will make Lux Sky renber black

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#33]
3ds max 2021
if in the scene there is a mesh with lux light material or a lux material with emission enabled a lux sky is added to the scene.
Adding any lux light object for example lux point, lux sun, lux spot, lux sky, the lux sky will render black

**Comment by OmidGhotbi** [comment]
It's not a bug. There is an option for it called "Auto default light", you can disable it in the light sitting panel inside renderer settings.

**Comment by OmidGhotbi** [comment]
For skylight you need to add a little bit of gain, for example, 2.2 gain multiplayer would be a good number for clear sky, Also use a proper exposer for it like auto linear plus gamma correction 2.2 with 512 sample.

**Comment by OmidGhotbi** [comment]
you need to add correct exposure to fix it.

**Comment by OmidGhotbi** [comment]
check for new solution so you do not need to change parameters

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta by adding an option for not render default light if any light adds in the scene, need to be used with exposure.
