### ISSUE TITLE
feature request render time

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#36]
Would be good to have somehow the rendering time information available.
or maybe as renderers does in 3ds max, in the lower left corner of the 3ds max UI, this information is available after rendering end.
Vray does deliver this information too in the same way, see image link for the position.
https://forums.luxcorerender.org/download/file.php?id=9369&mode=view

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta

**Comment by patro1** [comment]
in v0.8.7916-beta I noticed that I still need to link the body objects because some disappear in the render, not always, not in every scene, for example it doesn't happen with LuxTeaPot
The mapping works only if I add the unwrap UVW to the body objects, otherwise they render without texture.
Maybe the instancing and reference get broken on export. for body objects( i must check this)
