### ISSUE TITLE
3ds max 2021 Material Editor Crash

### ISSUE THREAD

**Issue by rs3dtouch** [LuxCoreRender/MaxToLux#37]
_Max 2021 (with latest SPs)_

Opening the Material Editor (Slate or Classic) and opening the Lux material category crashed Max.

It seems to render some preview thumbnails and then fails. Even when the scene itself is empty after a fresh start...

**Comment by OmidGhotbi** [comment]
Can you give me the exact name or type of material that causes the crash?
You can find it in the node-based material editor on the status bar when the crash happened.
If it's null material I already fixed it.
You can send me a screenshot of the crash in the LuxCore forum also.

**Comment by OmidGhotbi** [comment]
investigating new crash with 3dsmax 2021.3

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta
