### ISSUE TITLE
group issue

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#38]
When there are groups in the scene, may they visible and or on a separate layer which are off,:
they are all visible in the rendered image. 
There is no cons if the group helper is on same layer of its groped geometries or in a separete one, or is turned off by the layer.

**Comment by OmidGhotbi** [comment]
Thank to report, has been fixed in upcoming build.

**Comment by OmidGhotbi** [comment]
fixed in v0.8.1904-beta build.

**Comment by OmidGhotbi** [comment]
the problem back with object instancing

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta
