### ISSUE TITLE
3ds max crashes on mat editor 

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#39]
sometimes after working with a scene it happens that after reopening it, something chaneged..
you open the mat editor, for example in compact mode, "enable global rendering" is enabled, LuxCore start to render the slots one by one to update them, suddenly the process hang on a slot, max crashes instantly.
To avoid this, I have to restart max, open the mat editor in slate mode, unflag "enable global rendering" from the "option" menu in the slate mat editor, so that when i expand the "sample slots" LuxCore will not start updating the sample slots, which would crash max istantly.

**Comment by OmidGhotbi** [comment]
Fixed in build v0.8.2.5.

**Comment by OmidGhotbi** [comment]
crash on new mix material

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta
