### ISSUE TITLE
Lux Mix material mat editor bug

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#41]
Lux Mix material cause mat editor bug.
A Lux mix material which is in the material slot doesn't cause any issue while the scene is open.
After closing and reopening the scene, the scene might be corrupted, impossible to open, if it opens, it crashes on mat editor opening.
To can open the mat editor, is possible only in slate mode, raplace the lux mix material with another material, this will fix the issue.

**Comment by OmidGhotbi** [comment]
Thank you for the report, now it's been fixed.

**Comment by OmidGhotbi** [comment]
Fixed
