### ISSUE TITLE
lux sphere light bug (?)

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#46]
lux sphere light possible bug (?)
I just tried 2 times to render a scene adding a lux sphere light, in both occasion my computer freezed and crashed. I could only restart my computer.
The render started normally, but after few passes the ram usage get so huge that it killed everything.

**Comment by OmidGhotbi** [comment]
Fixed.

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta
