### ISSUE TITLE
some imported geometries disappear in render

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#47]
some imported geometries disappear in render, other not. To make them show in render i link the one which aren't visible in the render, to a geometry which is visible in render.

PS: Omid, in the chemistry scene i sent you, the flasks and the liquid are linked to the shelf, if you unlink them, you might see 2 flask disappaering from the render.

**Comment by OmidGhotbi** [comment]
I'll check that soon.

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta
