### ISSUE TITLE
Normal issue generate by the Mirror the transform

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#51]
Normal issue generate by the Mirrored transform of clone-copy-instanced geometry .
The issue is simple to reproduce, create a box or sphere, then mirror the sphere-box as instance, asign same material to the objects. The material should be at least a glossy 2 material with different color than the deffault grey.
At render time the instanced mirrored obeject will render like it has a matte material.
Most probably the mirroring causes a transform issue in the normals.

Edited: this behaviour is reported also for the Lux Light - emission flip normals (?) #53, but maybe it's caused by the same transform issue.
I must report that the when you create a plane which is intended to be a lux light plane,, depending on the use and position you need to flip the normals, but the render keeps being black, because the normals aren't translated as flipped to maxtolux. Mirroring the plane, doesn't affect the render neither. Only workaround is to rotate the light plane by 180°

edited edited: the mismatch in the render for mirror geometries are visible when using
 glossy2, 
 carpaint, 
 lux glass, 
 glossy translucent, 
 lux light, 
 Lux mix (has a bug as-reported), 
 Lux rough glass
 
![lux light](https://user-images.githubusercontent.com/74514605/111300221-1f44af00-8651-11eb-895b-f08fe3b748b4.jpg)

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta
![image](https://user-images.githubusercontent.com/164653/112606063-3edd9380-8e18-11eb-9311-3e6db06156d5.png)
