### ISSUE TITLE
Lux glass render black

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#52]
Lux glass render black in some cases, especially when the obeject has thickness. like a vase or a glass or bottle.

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta. of course, the glass has options for outbound of transparency and that can be used to control the effect that should be used with thick glasses, and that's a different case.

**Comment by patro1** [comment]
does "options for outbound of transparency" has a different name in the glass material setting? or is it yet not implemented? because I can't find it

**Comment by OmidGhotbi** [comment]
what option do you mean exactlly?

**Comment by patro1** [comment]
> Fixed in v0.8.7916-beta. of course, the glass has options for outbound of transparency and that can be used to control the effect that should be used with thick glasses, and that's a different case.

outbound of transparency as you wrote

**Comment by OmidGhotbi** [comment]
Wait i add more options to glass and for caustic that you will love.
![Screenshot 2021-04-18 182415](https://user-images.githubusercontent.com/164653/115152875-56084d80-a073-11eb-8cc7-f1eb27f78fbf.jpg)

**Comment by patro1** [comment]
will you share a nightly or create a new build given the latest improvments?
as i understand the settings for glass, like caustics, are hardcoded for now.

**Comment by OmidGhotbi** [comment]
the problem was not about the glass it's about something called SDS. I'll share it soon.
![002121](https://user-images.githubusercontent.com/164653/115310551-40c41980-a16e-11eb-909d-a86805bc646d.jpg)

**Comment by patro1** [comment]
What about dispersion and or abbe number, so to can render diamond with dispersion. does this needs to be implemented?

**Comment by OmidGhotbi** [comment]
i already add two remain parameters. it will be released very soon.

**Comment by OmidGhotbi** [comment]
Fixed
