### ISSUE TITLE
Lux Light - emission flip normals (?)

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#53]
Flip normals in the emission or Lux Light material UI doesn't work

Edited:
I must report that the when you create a plane which is intended to be a lux light plane,, depending on the use and position you need to flip the normals, but the render keeps being black, because the normals aren't translated as flipped to maxtolux. Mirroring the plane, doesn't affect the render neither. Only workaround is to rotate the light plane by 180°

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta by adding a flip normal in lux Light materials
