### ISSUE TITLE
Lux Metal fresnel texture

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#57]
Lux Metal fresnel texture slot doesn't work. 
Yo can add a map,, but at render time the color of metal is the one from the RGB color selector.

**Comment by patro1** [comment]
the metal types from the drop down menu are not working.
for example, selecting gold one expect to render yellow-gold, but it uses the color of the color selector which is by default grey.

**Comment by OmidGhotbi** [comment]
Fixed in v0.8.7916-beta
