### ISSUE TITLE
Lux cloth textured-issue

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#59]
Re-opening a scene which has textured Lux cloth in the scene. or in mat editor, 
1) load the material in mat editor if not available in its slots.
2) Open a texture, of Lux cloth, 
3) when trying to return to the material setting (so coming out from the texture menu), max crashes after a while because of ram usage.

**Comment by OmidGhotbi** [comment]
I can not reproduce the issue.

**Comment by patro1** [comment]
I found out how to replicate it. It is not happening only with cloth material but with all materials.
how to replicate by using compact material editor:
1) drag&drop a bitmap into a empty material slot.
2) in 2 different empty mat slot create 2 different lux matte material. let them call mat1 and mat2
3) drag&drop the bitmap from 1) into the diffuse slot of mat1, release as copy
4) drag&drop the bitmap from 1) into the diffuse slot of mat2, release as instance
5) click on the diffuse channel of mat1, to access the  bitmap setting, right after return to the main setting of mat1. it works
6) click on the diffuse channel of mat2, to access the  bitmap setting, right after return to the main setting of mat2. max is busy. after a bit it crashes.

**Comment by OmidGhotbi** [comment]
Those are serious steps to replicate the issue. I'll try that and see what's happening.
