### ISSUE TITLE
3ds max  2022 support

### ISSUE THREAD

**Issue by Ericka-dev** [LuxCoreRender/MaxToLux#60]
I know it is very early to ask and 3ds max  2022 just released, but it would be perfect if we have MaxToLux for 3dsmax 2022.

**Comment by OmidGhotbi** [comment]
Add support for 3ds Max 2022 in v0.8.7916-beta.
![Screenshot 2021-03-26 220418](https://user-images.githubusercontent.com/164653/112693870-aaa81680-8e81-11eb-9568-38197a540918.jpg)

**Comment by Ericka-dev** [comment]
amazing
