### ISSUE TITLE
3DS Max 2020 mat editor crash

### ISSUE THREAD

**Issue by Myirdin** [LuxCoreRender/MaxToLux#66]
Hi,

when i set Lux to renderer and open max 2020 material editor, max crashes.

Is this a known issue?

Maybe i forgot doing something during installation?

**Comment by OmidGhotbi** [comment]
Did you use the last version v0.8.2705 or later?

**Comment by Myirdin** [comment]
> Did you use the last version v0.8.2705 or later?

Hi, i use v0.8.2.7

**Comment by OmidGhotbi** [comment]
Please check the 3dsmax installation folder and inside "Maps" you should see "LuxMap" just rename it to "LuxMaps" and I think this will solve your problem.
In New build, I fixed it and it will be available in 2 days.
If it was the issue please confirm it here.

**Comment by Myirdin** [comment]
> Please check the 3dsmax installation folder and inside "Maps" you should see "LuxMap" just rename it to "LuxMaps" and I think this will solve your problem.
> In New build, I fixed it and it will be avilable in 2 days.

I'll do it. 

Thanks for quick reply!!

**Comment by Myirdin** [comment]
> Please check the 3dsmax installation folder and inside "Maps" you should see "LuxMap" just rename it to "LuxMaps" and I think this will solve your problem.
> In New build, I fixed it and it will be available in 2 days.
> If it was the issue please confirm it here.

I'm afraid the folder is already named "LuxMaps"

But i can wait a couple of days for the new build. However, thanks again for the quick reply

**Comment by OmidGhotbi** [comment]
If there is any special error message please upload it here or report in LuxCoreRender Forums. ScreenShot Before 3dsmax Crash can help a lot because it will show the material causing the crash.

**Comment by Myirdin** [comment]
![Max_Crash_Lux](https://user-images.githubusercontent.com/82443075/114541112-95d7cb00-9c56-11eb-9838-91695e11e4b7.JPG)
It happens each time material viewport updates reaches rendering " (Standard)"

See attached capture
![Max_Crash_Lux](https://user-images.githubusercontent.com/82443075/114541112-95d7cb00-9c56-11eb-9838-91695e11e4b7.JPG)

**Comment by OmidGhotbi** [comment]
So it is okay for other materials before standard and when it reaches the standard material crash

**Comment by Myirdin** [comment]
Yes, but only when i set luxcore as renderer. when another renderer is active, no problem

**Comment by Myirdin** [comment]
I may add that this occurs even with an empty scene, and the exact same problem appears in 3DS Max 2019.

**Comment by patro1** [comment]
Just a hint. Open the mat editor only in "slate" mode, and as fast as you can go to option-> set it to "manual update toggle", then go to utilities and reset the material editor.
maybe this will help you to work with maxtolux in the next days till new release willl be avialble. Of course if this hint might be a workaround for you report back.

**Comment by OmidGhotbi** [comment]
it is not possible for me to replicate the issue, i hate when that happened because there is no way to know what is the issue came from. perhaps conflict with another renderer.
I fixed many issues in the new build and it will be ready on Friday or Saturday. If this one not fixing your problem i will investigate the issue directly with you, perhaps giving you and debug version so i have at least an error number.

**Comment by OmidGhotbi** [comment]
Look at this, I just try to install a fresh one and no problem at all. I really appreciate you helping us investigate the problem.

https://user-images.githubusercontent.com/164653/114587425-f3374080-9c85-11eb-9521-22e717f5c0b8.mp4

**Comment by Myirdin** [comment]
I've tried making a fresh install, but it didn't solve the problem. i'll try the workaround with the "manual update" and come back to you.

**Comment by Myirdin** [comment]
New Problem.
I've disabled update renderings on the editor then opened one Lux Material. I tried to manually update this material preview and it crashed again.  See attached.
![max_lux_crash](https://user-images.githubusercontent.com/82443075/114668044-8dd46580-9d00-11eb-8086-f207cac28e2c.JPG)

**Comment by Myirdin** [comment]
If you need additionnal information (graphic card, other renderers installed), let me know.

**Comment by OmidGhotbi** [comment]
Are you able to render anything? did you remove the old plugin from add remove program first and try to install a new one?

**Comment by Myirdin** [comment]
Hi. I used add remove program. And Max to Lux is still in the renderers list. Can't find how to uninstall it properly...

**Comment by OmidGhotbi** [comment]
That's super strange it could be the source of the problem. one way is to remove it manually. remove these files in 3dsmax root : embree3.dll, luxcore.dll, OpenImageDenoise.dll, OpenImageIO_LuxCore.dll
![Screenshot 2021-04-14 105231](https://user-images.githubusercontent.com/164653/114682604-89637900-9d0f-11eb-800c-f74511431c1a.jpg)

in the plugin folder LuxMap2020.dlt, LuxMaterial2020.dlt,  LuxObjects2020.dlo, MaxToLux2020.dlr
![Screenshot 2021-04-14 105316](https://user-images.githubusercontent.com/164653/114682709-a26c2a00-9d0f-11eb-94d0-8409d1b95c0e.jpg)

inside plugin/en-US : LuxMap2020.dlt.mui, LuxMaterial2020.dlt.mui, LuxObjects2020.dlo.mui
![Screenshot 2021-04-14 105344](https://user-images.githubusercontent.com/164653/114682780-b1eb7300-9d0f-11eb-9775-38bf512bb247.jpg)

Also inside maps folder LuxMaps directory.
![Screenshot 2021-04-14 105412](https://user-images.githubusercontent.com/164653/114682843-c3347f80-9d0f-11eb-8dbc-846cac0bcc8b.jpg)

And it should be completely removed.
Then try to reinstall it.
After installation if it's not work again please try to rename "LuxMaps" to "LuxMap" inside the map folder and see if it make any change.

**Comment by OmidGhotbi** [comment]
If none of these work if it is possible to give me anydesk id or teamviewer id so i can check the issues myself, just an alternative solution of course if it's possible for you or perhaps wait for a new installer in just one or two days with more features.

**Comment by Myirdin** [comment]
Thanks for help. i'll try to uninstall it manually.

I'm afraid my directors won't allow anyone to inspect our computers but i can wait a few days for the next release.

I've just discovered your renderer.

**Comment by Myirdin** [comment]
So:
- After manual uninstall and fresh re-install. Same crash.
- After renaming LuxMaps to LuxMap: The crash occurs at the very beginning of the mat editor updating. It's new!

**Comment by OmidGhotbi** [comment]
i see, two options, first, wait for a new build that may fix the issue (i think there is something different cause the issue and that's new)
second, if you familiar with Anydesk or Teamviewer give me your id so i can check it by myself

**Comment by Myirdin** [comment]
I will wait for next build.

Thanks!

**Comment by OmidGhotbi** [comment]
it could be an issue with the GPU driver or conflict with other plugins. thank you for your time.

**Comment by Myirdin** [comment]
I have Vray installed in all my 3ds max versions.

For the GPU, it's a quadro p4000. Driver is up to date

**Comment by OmidGhotbi** [comment]
the strange part is material preview works until the standard material. that's really confusing.

**Comment by Myirdin** [comment]
It crashes in material preview for a Luxcore material (velvet one) when LuxMaps is renamed to LuxMap

**Comment by OmidGhotbi** [comment]
please just render a simple scene with just one object nothing else, and tell me is it working or not.

**Comment by Myirdin** [comment]
But i can't even apply a luxmaterial

**Comment by OmidGhotbi** [comment]
it doesn't matter, just see if it's working or not. i want the result so i can find the problem perhaps.
just a teapot and hit F9 that's all.

**Comment by Myirdin** [comment]
![Rendertest](https://user-images.githubusercontent.com/82443075/114689574-1f020700-9d16-11eb-8c81-e3f74e5c7624.JPG)
It Works

**Comment by OmidGhotbi** [comment]
Thank you, tomorrow night i will release a new build and try to consider your issue in it, we talk again after that.

**Comment by Myirdin** [comment]
Ok. good luck!

**Comment by Myirdin** [comment]
Hi.

I've installed the new build but the problem persists. I bet you didn't find a way to solve it for this version.

If you need any help/tests for this matter, don't hesitate to contact me.

**Comment by OmidGhotbi** [comment]
i just release a new build and i hope this one fixes the issue for you.

**Comment by Myirdin** [comment]
> i just release a new build and i hope this one fixes the issue for you.

Maybe you didn't see my previous post. didn't work with the new build. Exact same crash

**Comment by OmidGhotbi** [comment]
I'm really confused why it happens for you, it is a little bit unusual. by the way, finding the issue with helping us to improve LuxCore.
Can you check with LuxMark and tell me if it works for you especially the stress check.
Also, I'll try to send you a scene today later so you can just hit the render and see if the problem came from the material editor or the LuxCore itself on your side or maybe hardware-related.

**Comment by Myirdin** [comment]
LuxMark? What is it?

Ok for the test scene. Just don't send me a Max2022 version, i didn't install it

**Comment by OmidGhotbi** [comment]
https://github.com/LuxCoreRender/MaxToLux/blob/master/SampleScenes/DanishMood-Lux.zip
Just remember the first time you hit the render it will try to Compile the Kernels so it can take up to 5 minutes, it is not a bug and it is not a crash just wait and it will be fine.
As you request 3dsmax 2019 scene.

**Comment by OmidGhotbi** [comment]
https://github.com/LuxCoreRender/LuxMark/releases/tag/luxmark_v4.0alpha0
LuxMark is a benchmark and hardware test base on LuxCore it's pretty famous actually.

**Comment by Myirdin** [comment]
> https://github.com/LuxCoreRender/LuxMark/releases/tag/luxmark_v4.0alpha0
> LuxMark is a benchmark and hardware test base on LuxCore it's pretty famous actually.

Ok, i'll try it. never used other benchmarks that Vray...

**Comment by Myirdin** [comment]
Hi,

Everything goes fine with the Luxmark.

But error with the test scene. See attached
![Scene_test](https://user-images.githubusercontent.com/82443075/115018343-03366680-9eb8-11eb-9a59-2a027e71b6fc.JPG)

**Comment by OmidGhotbi** [comment]
Finally, an error message, error is related to windows local language. What windows language you use? the separator is "," instead of " ." I can work on it now.

**Comment by Myirdin** [comment]
I use French for Windows, because i'm french.

But i use English for other softwares.

**Comment by OmidGhotbi** [comment]
ok, thank you I'll try to set my windows language to french so i can have the same issue and fix it by tonight.
the quick fix is to change the separator from "," to "." in windows, so for every application, you have standards digit.
By the way, i will fix it tonight for sure. Thank you very much for the time you spend here.
![Screenshot 2021-04-16 140519](https://user-images.githubusercontent.com/164653/115021976-0122d680-9ebd-11eb-95bc-e1bdc793baac.jpg)

**Comment by Myirdin** [comment]
Glad it has helped.

I will wait for the fix next week as it would be better to leave digits as they are if any of my colleagues needs to use my computer.

Bye

**Comment by OmidGhotbi** [comment]
It's Done. now you can use it in the European language too. If you see any issue with that let me know because it's a new build. Start with the test scene that I sent to you a few posts earlier and then try other things.
In the LuxCoreRender forum, we have a great community that helping each other and if you have any questions you can ask.
[https://forums.luxcorerender.org/viewtopic.php?f=5&t=1010&start=560#p29626](url)
By the way, enchanté monsieur, J'habite aussi en France. 
![Screenshot 2021-04-16 185405](https://user-images.githubusercontent.com/164653/115058515-a356b480-9ee5-11eb-91b1-0ade401c0cbd.jpg)

**Comment by Myirdin** [comment]
Haha, enchanté aussi. Merci d'avoir réglé le problème, je le teste dès que possible.

Bonne journée!

**Comment by Myirdin** [comment]
Ok. it works now. Time to learn how to use it.

**Comment by OmidGhotbi** [comment]
Great, we try to provide a few scenes to show you how to work with it and of course a few video tutorials, but till then you can get help in the forum, there are many people that will be glad to help.
of course, you can try it yourself and see what will happen.
[luxforum](https://forums.luxcorerender.org/index.php)
[MaxToLux part](https://forums.luxcorerender.org/viewtopic.php?f=5&t=1010&start=570)

**Comment by OmidGhotbi** [comment]
Fixed
