### ISSUE TITLE
HDRI Gamma is not correct at the start point

### ISSUE THREAD

**Issue by OmidGhotbi** [LuxCoreRender/MaxToLux#69]
HDRI Gamma is not correct at the start point and that will cause harsh color in the render.

**Comment by OmidGhotbi** [comment]
Works better with new settings as the default settings.
![Screenshot 2021-04-19 002229](https://user-images.githubusercontent.com/164653/115162732-633e3000-a0a5-11eb-9945-41789472f433.jpg)

**Comment by patro1** [comment]
looks as it should now. great job

**Comment by patro1** [comment]
those pompon looks made for that hdr lol

**Comment by OmidGhotbi** [comment]
Replace these files in the plugin folder like the last time and enjoy the new look.
[MaxToLux2021.zip](https://github.com/LuxCoreRender/MaxToLux/files/6332349/MaxToLux2021.zip)

**Comment by patro1** [comment]
downloaded. I'll try tomorrow.

**Comment by OmidGhotbi** [comment]
![file](https://user-images.githubusercontent.com/164653/115163279-92a26c00-a0a8-11eb-9871-5ff254b015b1.jpg)
Nice.
Gamma correction 2.2 for Tonemap in the render settings.

**Comment by OmidGhotbi** [comment]
add it to the new build.
[v0.8.9124](https://github.com/LuxCoreRender/MaxToLux/releases/tag/v0.8.91)

**Comment by patro1** [comment]
The rotation  deviation of the ibl between viewport and render is 90°.
btw perspective view rendering works great now

**Comment by OmidGhotbi** [comment]
Thank you for the information.

**Comment by patro1** [comment]
I think now that the gamma or brightness of the visible portion of the IBL hdr in the render is too high. 
while the harsh effect is gone, which is good.
as you can see, the used hdr is a night hdr, while rendered it looks like almost day
![2021-04-19_133219](https://user-images.githubusercontent.com/74514605/115237106-7213f980-a11c-11eb-8804-8f8d267de5f6.jpg)

**Comment by OmidGhotbi** [comment]
Do not worry i add an option for it so in the next build everyone is able to change it as they like. the optimum setting for the day time is 0.5 and for the night is 1.

**Comment by OmidGhotbi** [comment]
of course, you can send me the project so i check if anything else wrong with it. but i think the HDRi light parameter will solve your problem.

**Comment by OmidGhotbi** [comment]
Hdri rotation is fixed now.
![Screenshot 2021-04-19 150500](https://user-images.githubusercontent.com/164653/115241208-d8028000-a120-11eb-92ae-1a3317e616bc.jpg)

**Comment by patro1** [comment]
> of course, you can send me the project so i check if anything else wrong with it. but i think the HDRi light parameter will solve your problem.
great, and great for the rotation too. now it will be possible to use LuxSun and the related ibl hdr to render correctly a scene using smart IBL

**Comment by OmidGhotbi** [comment]
I think so, but we need more tests before be certain.

**Comment by patro1** [comment]
> I think so, but we need more tests before be certain.

for this I've already prepeared a max scene where the sun is oriented with the hdr

**Comment by patro1** [comment]
> I think so, but we need more tests before be certain.

here the scene i've prepaered.
[luxcore barcelona roof pool.zip](https://github.com/LuxCoreRender/MaxToLux/files/6339357/luxcore.barcelona.roof.pool.zip)
inside there is a lux sun and sky which are aligned with the sun of the HDR or the huge JPG
the Lux sky is off, the Lux sun has intensiti of 0.01
See if you find a way to get sun and ibl to work together 

there is a pool also which is in camera match with the ibl. 
this is how luxcore renders it for now, of course in my render the ibl is still rotated, and the gamma can't be adjusted yet.
![luxcore test](https://user-images.githubusercontent.com/74514605/115308718-74517480-a16b-11eb-83d5-73c96e5c88a8.jpg)
this is how it is rendered by vray. vray of course can set several hdr for ref and refraction and a background ibl too.
![vray test](https://user-images.githubusercontent.com/74514605/115308741-7b788280-a16b-11eb-9fbc-d0613fd47302.jpg)

**Comment by OmidGhotbi** [comment]
Very nice, the new release will be available soon.

**Comment by patro1** [comment]
catch shadow, or shadowcatcher isn't supported yet by maxtolux.. i'm sure in the end I'll get a nice image as with vray.

**Comment by OmidGhotbi** [comment]
you mean shadowcatcher.enable ? i will put it on the to-do list. it is a general option for all materials.

**Comment by patro1** [comment]
> you mean shadowcatcher.enable ? i will put it on the to-do list. it is a general option for all materials.

yes that one. the plane under the 3 sphere is a lux matte with catch shadow enabled, but of course it's not working

**Comment by OmidGhotbi** [comment]
Fixed
