### ISSUE TITLE
Support for face mapping UV set

### ISSUE THREAD

**Issue by OmidGhotbi** [LuxCoreRender/MaxToLux#70]
Add Support for face mapping UV set

**Comment by patro1** [comment]
is this also about the missing uv mapping on body objects?

**Comment by OmidGhotbi** [comment]
yes, body object and any other object that uses face mapping and pixel paint. of course, that's not a good UV set and you can see the problem with it, but just for the support it as an option.

**Comment by OmidGhotbi** [comment]
Fixed
